name: CI Angular 

on: 
  push:
    branches: [ "relase"]
  pull_request:
    branches: [ "relase"]

jobs:
  relase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
            node-version: 18.x

      - name: Setup /ng build
        run: npm ci

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
